sonar.projectKey=SonarSource_terraform-provider-sonarqube
sonar.organization=sonarsource

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go
sonar.cpd.exclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=main.go
